name: Hellobot Dev Report Webview Docker Image CI

on:
  push:
    branches: [ dev-report-web-deploy ]

jobs:
  build:
    runs-on: act-hlb-report-web

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_K8S }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_K8S }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get image tag(verion)
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "::set-output name=version::$VERSION"
    - name: Build, tag, and push image to Amazon ECR
      id: image-info
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hlb/etc
        IMAGE_TAG: ${{ steps.image.outputs.version }}
      run: |
        echo "registry=$ECR_REGISTRY" >> $GITHUB_ENV
        echo "repository=$ECR_REPOSITORY" >> $GITHUB_ENV
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV
        echo "::set-output name=ecr_repository::$ECR_REPOSITORY"
        echo "::set-output name=image_tag::$IMAGE_TAG"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout kustomize repository
      uses: actions/checkout@v2
      with:
        repository: thingsflow/common-infra-eks-deploy
        ref: main
        token: ${{ secrets.ACTION_TOKEN_K8S }}
        path: common-infra-eks-deploy

    - name: Update Kubernetes resources
      run: |
        echo ${{ env.registry }}
        echo ${{ env.repository }}
        echo ${{ env.image_tag }}
        cd common-infra-eks-deploy/overlays/hlb/dev/apn2/report-webview/
        kustomize edit set image ${{ env.registry }}/${{ env.repository }}=${{ env.registry }}/${{ env.repository }}:${{ env.image_tag }}
        cat kustomization.yaml
    - name: Commit files
      run: |
        cd common-infra-eks-deploy
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git commit -am "Update image tag"
        git push -u origin main